#!/bin/bash

CREDS="/run/user/$(id -u)/kiosk-creds"

while true
do
    # 1. start login
    systemctl --user start kiosk-login.service

    # 2. wait until login exits
    while systemctl --user is-active kiosk-login.service >/dev/null
    do
        sleep 0.5
    done

    # 3. run RDP
    if [ ! -f "$CREDS" ]; then
        continue
    fi
    
    systemctl --user start kiosk-rdp.service

    # 4. wait until RDP exits
    while systemctl --user is-active kiosk-rdp.service >/dev/null
    do
        sleep 0.5
    done

done
